#!/bin/sh

./split-multicol > misc/multicol.txt

./extract corvallis/*.txt | ./geocode > counts-corvallis.csv
./extract oakland/*.txt oakland/*/*.txt | ./geocode > counts-oakland.csv
./extract misc/*.txt | ./geocode > counts-misc.csv
./extract sanjose/*.txt | ./geocode > counts-sanjose.csv
./extract eugene/*.txt | ./geocode > counts-eugene.csv

find rtc -name '*.txt' -print0 | xargs -0 ./extract > counts-rtc.csv
find portland -name '*.txt' -print0 | xargs -0 ./extract | (cd ../kc-traffic-counts; ./geocode-portland) > counts-portland.csv
find sf -name '*.txt' -print0 | xargs -0 ./extract | LC_ALL=C sort | (cd ../sf-traffic-counts; ./geocode) > counts-sf.csv
find dc -name '*.txt' -print0 | xargs -0 ./extract | LC_ALL=C sort | ./extract-report-addresses > counts-dc.csv
