#!/usr/bin/perl

while (<>) {
	chomp;
	($id, $name, $id2, $date, $time, @fields) = split(/,/);

	if ($time =~ /^(\d+):(\d+)\s*-+\s*(\d+):(\d+)$/) {
		($h1, $m1, $h2, $m2) = ($1, $2, $3, $4);
		$dur = ($h2 * 60 + $m2) - ($h1 * 60 + $m1);

		$walk = $fields[12] + $fields[13] + $fields[14] + $fields[15];

		# print "$fields[12], $fields[13], $fields[14], $fields[15]  $walk  ";
		printf("%d /%s ", $walk * 60 / $dur, $dur);

		print "$id,$name,$id2,$date,";
		printf("%02d:%02d,", $h1, $m1);

		for ($i = 0; $i < 20; $i++) {
			printf("%d,", $fields[$i] * 60 / $dur);
		}

		for ($i = 20; $i <= $#fields; $i++) {
			print "$fields[$i],";
		}

		print "\n";
	} else {
		unless ($seen{$time}) {
			print STDERR "$ARGV: Don't know what to do with time interval $time\n";
		}

		$seen{$time} = 1;
	}
}
