#!/usr/bin/perl

$max = 50;

for $file (<misc/*.txt>, <portland/*.txt>, <corvallis/*.txt>) {
	$out = "$file.tmp";
	print STDERR "$file $out\n";

	open(IN, "$file");
	open(OUT, ">$out");
	$page = "";
	$n = 0;
	while (<IN>) {
		if (/\014/) {
			if ($n < $max || $page =~ /Type of peak hour/ || $page =~ /Total Vehicle Summary/ || $page =~ /Groups Printed/) {
				print OUT $page;
			}

			$page = "";
			$n++;
		}

		$page .= $_;
	}
	if ($n < $max || $page =~ /Type of peak hour/ || $page =~ /Total Vehicle Summary/ || $page =~ /Groups Printed/) {
		print OUT $page;
	}
	close(IN);
	close(OUT);

	rename($out, $file);
}
